# Generated by Django 2.2.2 on 2019-06-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, verbose_name='matricula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'alunos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='nome')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='codigo')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplina',
                'db_table': 'disciplinas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='comment')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='rating')),
                ('deliveryForecast', models.DateTimeField(blank=True, null=True, verbose_name='deliveryForecast')),
                ('ordered', models.DateTimeField(blank=True, null=True, verbose_name='ordered')),
                ('printing', models.DateTimeField(blank=True, null=True, verbose_name='printing')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='finished')),
                ('delivered', models.DateTimeField(blank=True, null=True, verbose_name='delivered')),
                ('canceled', models.DateTimeField(blank=True, null=True, verbose_name='canceled')),
                ('cancelId', models.CharField(blank=True, max_length=30, null=True, verbose_name='cancelId')),
                ('paymentLink', models.CharField(blank=True, max_length=300, null=True, verbose_name='paymentLink')),
                ('totalValue', models.FloatField(default=0.0, verbose_name='totalValue')),
                ('status', models.CharField(blank=True, max_length=30, null=True, verbose_name='status')),
                ('paymentType', models.CharField(default='money', max_length=30, verbose_name='paymentType')),
                ('trelloCardId', models.CharField(blank=True, max_length=40, null=True, verbose_name='trelloCardId')),
                ('usable', models.BooleanField(verbose_name='usable')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'order',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'professores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='nome')),
                ('alunos', models.ManyToManyField(to='gerenciaTurmas.Alunos')),
                ('disciplina', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciaTurmas.Disciplinas')),
                ('professor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciaTurmas.Professores')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turmas',
                'ordering': ['id'],
            },
        ),
    ]
