# Generated by Django 2.2.2 on 2019-06-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTurmas', '0002_disciplinas_cargahoraria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='turmas',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaTurmas.Disciplinas'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaTurmas.Professores'),
        ),
    ]
