# Generated by Django 2.2.2 on 2019-06-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTurmas', '0003_auto_20190621_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('enunciado', models.CharField(max_length=250, verbose_name='enunciado')),
                ('alternativa1', models.CharField(max_length=250, verbose_name='alternativa1')),
                ('alternativa2', models.CharField(max_length=250, verbose_name='alternativa2')),
                ('alternativa3', models.CharField(max_length=250, verbose_name='alternativa3')),
                ('alternativa4', models.CharField(max_length=250, verbose_name='alternativa4')),
                ('correto', models.IntegerField(blank=True, null=True, verbose_name='correto')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaTurmas.Disciplinas')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'db_table': 'questoes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaTurmas.Disciplinas')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaTurmas.Professores')),
                ('questoes', models.ManyToManyField(to='gerenciaTurmas.Questoes')),
            ],
            options={
                'verbose_name': 'Avalição',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'avaliacao',
                'ordering': ['id'],
            },
        ),
    ]
