# Generated by Django 2.2.2 on 2019-06-24 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTurmas', '0004_avaliacao_questoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaTurmas.Alunos')),
            ],
            options={
                'verbose_name': 'Resolução',
                'verbose_name_plural': 'Resoluções',
                'db_table': 'resolucao',
                'ordering': ['avaliacao'],
            },
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['id'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_aluno', models.CharField(max_length=250, verbose_name='Resposta')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaTurmas.Questoes')),
                ('resolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaTurmas.Resolucao')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'db_table': 'resposta',
                'ordering': ['questao'],
            },
        ),
        migrations.AddField(
            model_name='resolucao',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaTurmas.Avaliacao'),
        ),
    ]
