# Generated by Django 2.2.2 on 2019-06-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTurmas', '0005_auto_20190624_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucao',
            name='nota',
            field=models.FloatField(blank=True, null=True, verbose_name='nota'),
        ),
    ]
