# Generated by Django 2.2.2 on 2019-06-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTurmas', '0006_resolucao_nota'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resolucao',
            unique_together={('aluno', 'avaliacao')},
        ),
    ]
