# Generated by Django 2.2.2 on 2019-06-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTurmas', '0007_auto_20190624_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='questoes',
            field=models.ManyToManyField(blank=True, null=True, to='gerenciaTurmas.Questoes'),
        ),
    ]
