# Generated by Django 2.2.2 on 2019-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTurmas', '0008_auto_20190625_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='questoes',
            field=models.ManyToManyField(blank=True, to='gerenciaTurmas.Questoes'),
        ),
    ]
